logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = false
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced eXtended"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = "custom-branding-icon-revancify-blue"                                                 # whitespace seperated list of patches to exclude (multiline strings are not supported)
included-patches = "custom-branding-icon-mmt materialyou"                                                 # whitespace seperated list of patches to include
version = "auto"                                                      # 'auto', 'latest' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx"

[Music]
build-mode = "both"
app-name = "YouTube-Music"
excluded-patches = "custom-branding-icon-revancify-blue"
included-patches = "custom-branding-icon-mmt"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx"
apkmirror-arch = "both"
